version: '3'
services:
  strapi:
    build:
      context: .
      dockerfile: ./docker/strapi/Dockerfile
    ports:
      - 1337:1337
  next:
    build:
      context: .
      dockerfile: ./docker/next/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - strapi
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./docker/nginx/Dockerfile
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - next
