version: '3'
services:
  strapi:
    build:
      context: .
      dockerfile: ./docker/strapi/Dockerfile
    ports:
      - 1337:1337
    networks:
      - mynetwork

  next:
    build:
      context: .
      dockerfile: ./docker/next/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - strapi
    networks:
      - mynetwork
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - next
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
