version: '3'
services:
  strapi:
    build:
      context: ./strapi-app
      dockerfile: Dockerfile
    ports:
      - 1337:1337

  next:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000