import Head from 'next/head'
import DefaultLayout from '@/components/layouts/default'
import Script from 'next/script'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Главная страница</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" defer></Script>
      <div className="container-xxl bg-white p-0">
        <div className="container-xxl position-relative p-0">
          <DefaultLayout>
            <div className="container-xxl py-5 bg-primary hero-header mb-5">
              <div className="container my-5 py-5 px-lg-5">
                <div className="row g-5">
                  <div className="col-lg-6 pt-5 text-center text-lg-start">
                    <h1 className="display-4 text-white mb-4 animated slideInLeft">Shared Hosting</h1>
                    <p className="text-white animated slideInLeft">Tempor rebum no at dolore lorem clita rebum rebum ipsum rebum stet dolor sed justo kasd.</p>
                    <h1 className="text-white mb-4 animated slideInLeft">
                      <small className="align-top fw-normal" style={{ fontSize: '15px', lineHeight: '25px' }}>Starting:</small>
                      <span>$2.49</span>
                      <small className="align-bottom fw-normal" style={{ fontSize: '15px', lineHeight: '33px' }}>/ Mo</small>
                    </h1>
                    <Link href="/" className="btn btn-secondary py-sm-3 px-sm-5 me-3 animated slideInLeft">Get Started Now</Link>
                  </div>
                  <div className="col-lg-6 text-center text-lg-start">
                    <img className="img-fluid animated zoomIn" src="/img/hero.png" alt="" />
                  </div>
                </div>
              </div>
            </div>
            <div>
              <div className="modal fade" id="searchModal" tabIndex={-1}>
                <div className="modal-dialog modal-fullscreen">
                  <div className="modal-content" style={{ background: 'rgba(29, 40, 51, 0.8)' }}>
                    <div className="modal-header border-0">
                      <button type="button" className="btn bg-white btn-close" data-bs-dismiss="modal" aria-label="Close" />
                    </div>
                    <div className="modal-body d-flex align-items-center justify-content-center">
                      <div className="input-group" style={{ maxWidth: '600px' }}>
                        <input type="text" className="form-control bg-transparent border-light p-3" placeholder="Type search keyword" />
                        <button className="btn btn-light px-4"><i className="bi bi-search" /></button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="container-xxl domain mb-5" style={{ marginTop: '90px' }}>
                <div className="container px-lg-5">
                  <div className="row justify-content-center">
                    <div className="col-lg-10">
                      <div className="section-title position-relative text-center mx-auto mb-4 pb-4 wow fadeInUp" data-wow-delay="0.1s" style={{ maxWidth: '600px' }}>
                        <h1 className="mb-3">Search Your Domain</h1>
                        <p className="mb-1">Vero justo sed sed vero clita amet. Et justo vero sea diam elitr amet ipsum eos ipsum clita duo sed. Sed vero sea diam erat vero elitr sit clita.</p>
                      </div>
                      <div className="position-relative w-100 my-3 wow fadeInUp" data-wow-delay="0.3s">
                        <input className="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Enter your domain name" />
                        <button type="button" className="btn btn-primary py-2 px-3 position-absolute top-0 end-0 mt-2 me-2">Search</button>
                      </div>
                      <div className="row g-3 wow fadeInUp" data-wow-delay="0.5s">
                        <div className="col-lg-2 col-md-3 col-sm-4 col-6 text-center">
                          <h5 className="fw-bold text-primary mb-1">.com</h5>
                          <p className="mb-0">$9.99/year</p>
                        </div>
                        <div className="col-lg-2 col-md-3 col-sm-4 col-6 text-center">
                          <h5 className="fw-bold text-primary mb-1">.net</h5>
                          <p className="mb-0">$9.99/year</p>
                        </div>
                        <div className="col-lg-2 col-md-3 col-sm-4 col-6 text-center">
                          <h5 className="fw-bold text-primary mb-1">.org</h5>
                          <p className="mb-0">$9.99/year</p>
                        </div>
                        <div className="col-lg-2 col-md-3 col-sm-4 col-6 text-center">
                          <h5 className="fw-bold text-primary mb-1">.us</h5>
                          <p className="mb-0">$9.99/year</p>
                        </div>
                        <div className="col-lg-2 col-md-3 col-sm-4 col-6 text-center">
                          <h5 className="fw-bold text-primary mb-1">.eu</h5>
                          <p className="mb-0">$9.99/year</p>
                        </div>
                        <div className="col-lg-2 col-md-3 col-sm-4 col-6 text-center">
                          <h5 className="fw-bold text-primary mb-1">.co.uk</h5>
                          <p className="mb-0">$9.99/year</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="container-xxl py-5">
                <div className="container px-lg-5">
                  <div className="row g-5 align-items-center">
                    <div className="col-lg-7 wow fadeInUp" data-wow-delay="0.1s">
                      <div className="section-title position-relative mb-4 pb-4">
                        <h1 className="mb-2">Welcome to GreenHost</h1>
                      </div>
                      <p className="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit clita duo justo magna dolore erat amet</p>
                      <div className="row g-3">
                        <div className="col-sm-4 wow fadeIn" data-wow-delay="0.1s">
                          <div className="bg-light rounded text-center p-4">
                            <i className="fa fa-users-cog fa-2x text-primary mb-2" />
                            <h2 className="mb-1" data-toggle="counter-up">1234</h2>
                            <p className="mb-0">Experts</p>
                          </div>
                        </div>
                        <div className="col-sm-4 wow fadeIn" data-wow-delay="0.3s">
                          <div className="bg-light rounded text-center p-4">
                            <i className="fa fa-users fa-2x text-primary mb-2" />
                            <h2 className="mb-1" data-toggle="counter-up">1234</h2>
                            <p className="mb-0">Clients</p>
                          </div>
                        </div>
                        <div className="col-sm-4 wow fadeIn" data-wow-delay="0.5s">
                          <div className="bg-light rounded text-center p-4">
                            <i className="fa fa-check fa-2x text-primary mb-2" />
                            <h2 className="mb-1" data-toggle="counter-up">1234</h2>
                            <p className="mb-0">Projects</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-5">
                      <img className="img-fluid wow zoomIn" data-wow-delay="0.5s" src="img/about.png" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="container-xxl py-5">
                <div className="container px-lg-5">
                  <div className="section-title position-relative text-center mx-auto mb-5 pb-4 wow fadeInUp" data-wow-delay="0.1s" style={{ maxWidth: '600px' }}>
                    <h1 className="mb-3">Our Hosting Plans</h1>
                    <p className="mb-1">Vero justo sed sed vero clita amet. Et justo vero sea diam elitr amet ipsum eos ipsum clita duo sed. Sed vero sea diam erat vero elitr sit clita.</p>
                  </div>
                  <div className="row gy-5 gx-4">
                    <div className="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
                      <div className="position-relative shadow rounded border-top border-5 border-primary">
                        <div className="d-flex align-items-center justify-content-center position-absolute top-0 start-50 translate-middle bg-primary rounded-circle" style={{ width: '45px', height: '45px', marginTop: '-3px' }}>
                          <i className="fa fa-share-alt text-white" />
                        </div>
                        <div className="text-center border-bottom p-4 pt-5">
                          <h4 className="fw-bold">Share Hosting</h4>
                          <p className="mb-0">Eirmod erat dolor amet est clita lorem erat justo rebum elitr eos</p>
                        </div>
                        <div className="text-center border-bottom p-4">
                          <p className="text-primary mb-1">Latest Offer - <strong>Save 30%</strong></p>
                          <h1 className="mb-3">
                            <small className="align-top" style={{ fontSize: '22px', lineHeight: '45px' }}>$</small>2.49<small className="align-bottom" style={{ fontSize: '16px', lineHeight: '40px' }}>/ Month</small>
                          </h1>
                          <a className="btn btn-primary px-4 py-2" href="#">Buy Now</a>
                        </div>
                        <div className="p-4">
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />100 GB Disk Space</p>
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />Unlimited Bandwith</p>
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />Upgrade to Positive SSL</p>
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />Automatic Malware Removal</p>
                          <p className="mb-0"><i className="fa fa-check text-primary me-3" />30 Days Money Back Guarantee</p>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.4s">
                      <div className="position-relative shadow rounded border-top border-5 border-secondary">
                        <div className="d-flex align-items-center justify-content-center position-absolute top-0 start-50 translate-middle bg-secondary rounded-circle" style={{ width: '45px', height: '45px', marginTop: '-3px' }}>
                          <i className="fa fa-server text-white" />
                        </div>
                        <div className="text-center border-bottom p-4 pt-5">
                          <h4 className="fw-bold">VPS Hosting</h4>
                          <p className="mb-0">Eirmod erat dolor amet est clita lorem erat justo rebum elitr eos</p>
                        </div>
                        <div className="text-center border-bottom p-4">
                          <p className="text-primary mb-1">Latest Offer - <strong>Save 30%</strong></p>
                          <h1 className="mb-3">
                            <small className="align-top" style={{ fontSize: '22px', lineHeight: '45px' }}>$</small>5.49<small className="align-bottom" style={{ fontSize: '16px', lineHeight: '40px' }}>/ Month</small>
                          </h1>
                          <a className="btn btn-secondary px-4 py-2" href="#">Buy Now</a>
                        </div>
                        <div className="p-4">
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />100 GB Disk Space</p>
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />Unlimited Bandwith</p>
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />Upgrade to Positive SSL</p>
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />Automatic Malware Removal</p>
                          <p className="mb-0"><i className="fa fa-check text-primary me-3" />30 Days Money Back Guarantee</p>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                      <div className="position-relative shadow rounded border-top border-5 border-primary">
                        <div className="d-flex align-items-center justify-content-center position-absolute top-0 start-50 translate-middle bg-primary rounded-circle" style={{ width: '45px', height: '45px', marginTop: '-3px' }}>
                          <i className="fa fa-cog text-white" />
                        </div>
                        <div className="text-center border-bottom p-4 pt-5">
                          <h4 className="fw-bold">Dedi Hosting</h4>
                          <p className="mb-0">Eirmod erat dolor amet est clita lorem erat justo rebum elitr eos</p>
                        </div>
                        <div className="text-center border-bottom p-4">
                          <p className="text-primary mb-1">Latest Offer - <strong>Save 30%</strong></p>
                          <h1 className="mb-3">
                            <small className="align-top" style={{ fontSize: '22px', lineHeight: '45px' }}>$</small>11.49<small className="align-bottom" style={{ fontSize: '16px', lineHeight: '40px' }}>/ Month</small>
                          </h1>
                          <a className="btn btn-primary px-4 py-2" href="#">Buy Now</a>
                        </div>
                        <div className="p-4">
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />100 GB Disk Space</p>
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />Unlimited Bandwith</p>
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />Upgrade to Positive SSL</p>
                          <p className="border-bottom pb-3"><i className="fa fa-check text-primary me-3" />Automatic Malware Removal</p>
                          <p className="mb-0"><i className="fa fa-check text-primary me-3" />30 Days Money Back Guarantee</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="container-xxl py-5">
                <div className="container px-lg-5">
                  <div className="section-title position-relative text-center mx-auto mb-5 pb-4 wow fadeInUp" data-wow-delay="0.1s" style={{ maxWidth: '600px' }}>
                    <h1 className="mb-3">Shared VS Dedicated Server</h1>
                    <p className="mb-1">Vero justo sed sed vero clita amet. Et justo vero sea diam elitr amet ipsum eos
                      ipsum clita duo sed. Sed vero sea diam erat vero elitr sit clita.</p>
                  </div>
                  <div className="row g-5 comparison position-relative">
                    <div className="col-lg-6 pe-lg-5">
                      <div className="section-title position-relative mx-auto mb-4 pb-4">
                        <h3 className="fw-bold mb-0">Shared Server</h3>
                      </div>
                      <div className="row gy-3 gx-5">
                        <div className="col-sm-6 wow fadeIn" data-wow-delay="0.1s">
                          <i className="fa fa-server fa-3x text-primary mb-3" />
                          <h5 className="fw-bold">99.99% Uptime</h5>
                          <p>Ipsum dolor diam stet stet kasd diam sea stet sed rebum dolor ipsum</p>
                        </div>
                        <div className="col-sm-6 wow fadeIn" data-wow-delay="0.3s">
                          <i className="fa fa-shield-alt fa-3x text-primary mb-3" />
                          <h5 className="fw-bold">100% Secured</h5>
                          <p>Ipsum dolor diam stet stet kasd diam sea stet sed rebum dolor ipsum</p>
                        </div>
                        <div className="col-sm-6 wow fadeIn" data-wow-delay="0.5s">
                          <i className="fa fa-cog fa-3x text-primary mb-3" />
                          <h5 className="fw-bold">Control Panel</h5>
                          <p>Ipsum dolor diam stet stet kasd diam sea stet sed rebum dolor ipsum</p>
                        </div>
                        <div className="col-sm-6 wow fadeIn" data-wow-delay="0.7s">
                          <i className="fa fa-headset fa-3x text-primary mb-3" />
                          <h5 className="fw-bold">24/7 Support</h5>
                          <p>Ipsum dolor diam stet stet kasd diam sea stet sed rebum dolor ipsum</p>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-6 ps-lg-5">
                      <div className="section-title position-relative mx-auto mb-4 pb-4">
                        <h3 className="fw-bold mb-0">Dedicated Server</h3>
                      </div>
                      <div className="row gy-3 gx-5">
                        <div className="col-sm-6 wow fadeIn" data-wow-delay="0.1s">
                          <i className="fa fa-server fa-3x text-secondary mb-3" />
                          <h5 className="fw-bold">99.99% Uptime</h5>
                          <p>Ipsum dolor diam stet stet kasd diam sea stet sed rebum dolor ipsum</p>
                        </div>
                        <div className="col-sm-6 wow fadeIn" data-wow-delay="0.3s">
                          <i className="fa fa-shield-alt fa-3x text-secondary mb-3" />
                          <h5 className="fw-bold">100% Secured</h5>
                          <p>Ipsum dolor diam stet stet kasd diam sea stet sed rebum dolor ipsum</p>
                        </div>
                        <div className="col-sm-6 wow fadeIn" data-wow-delay="0.5s">
                          <i className="fa fa-cog fa-3x text-secondary mb-3" />
                          <h5 className="fw-bold">Control Panel</h5>
                          <p>Ipsum dolor diam stet stet kasd diam sea stet sed rebum dolor ipsum</p>
                        </div>
                        <div className="col-sm-6 wow fadeIn" data-wow-delay="0.7s">
                          <i className="fa fa-headset fa-3x text-secondary mb-3" />
                          <h5 className="fw-bold">24/7 Support</h5>
                          <p>Ipsum dolor diam stet stet kasd diam sea stet sed rebum dolor ipsum</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
                <div className="container px-lg-5">
                  <div className="owl-carousel testimonial-carousel">
                    <div className="testimonial-item position-relative bg-light border-top border-5 border-primary rounded p-4 my-4">
                      <div className="d-flex align-items-center justify-content-center position-absolute top-0 start-0 ms-5 translate-middle bg-primary rounded-circle" style={{ width: '45px', height: '45px', marginTop: '-3px' }}>
                        <i className="fa fa-quote-left text-white" />
                      </div>
                      <p className="mt-3">Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                      <div className="d-flex align-items-center">
                        <img className="img-fluid flex-shrink-0 rounded-circle" src="img/testimonial-1.jpg" style={{ width: '50px', height: '50px' }} />
                        <div className="ps-3">
                          <h6 className="fw-bold mb-1">Client Name</h6>
                          <small>Profession</small>
                        </div>
                      </div>
                    </div>
                    <div className="testimonial-item position-relative bg-light border-top border-5 border-primary rounded p-4 my-4">
                      <div className="d-flex align-items-center justify-content-center position-absolute top-0 start-0 ms-5 translate-middle bg-primary rounded-circle" style={{ width: '45px', height: '45px', marginTop: '-3px' }}>
                        <i className="fa fa-quote-left text-white" />
                      </div>
                      <p className="mt-3">Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                      <div className="d-flex align-items-center">
                        <img className="img-fluid flex-shrink-0 rounded-circle" src="img/testimonial-2.jpg" style={{ width: '50px', height: '50px' }} />
                        <div className="ps-3">
                          <h6 className="fw-bold mb-1">Client Name</h6>
                          <small>Profession</small>
                        </div>
                      </div>
                    </div>
                    <div className="testimonial-item position-relative bg-light border-top border-5 border-primary rounded p-4 my-4">
                      <div className="d-flex align-items-center justify-content-center position-absolute top-0 start-0 ms-5 translate-middle bg-primary rounded-circle" style={{ width: '45px', height: '45px', marginTop: '-3px' }}>
                        <i className="fa fa-quote-left text-white" />
                      </div>
                      <p className="mt-3">Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                      <div className="d-flex align-items-center">
                        <img className="img-fluid flex-shrink-0 rounded-circle" src="img/testimonial-3.jpg" style={{ width: '50px', height: '50px' }} />
                        <div className="ps-3">
                          <h6 className="fw-bold mb-1">Client Name</h6>
                          <small>Profession</small>
                        </div>
                      </div>
                    </div>
                    <div className="testimonial-item position-relative bg-light border-top border-5 border-primary rounded p-4 mt-4">
                      <div className="d-flex align-items-center justify-content-center position-absolute top-0 start-0 ms-5 translate-middle bg-primary rounded-circle" style={{ width: '45px', height: '45px', marginTop: '-3px' }}>
                        <i className="fa fa-quote-left text-white" />
                      </div>
                      <p className="mt-3">Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                      <div className="d-flex align-items-center">
                        <img className="img-fluid flex-shrink-0 rounded-circle" src="img/testimonial-4.jpg" style={{ width: '50px', height: '50px' }} />
                        <div className="ps-3">
                          <h6 className="fw-bold mb-1">Client Name</h6>
                          <small>Profession</small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="container-xxl py-5">
                <div className="container px-lg-5">
                  <div className="section-title position-relative text-center mx-auto mb-5 pb-4 wow fadeInUp" data-wow-delay="0.1s" style={{ maxWidth: '600px' }}>
                    <h1 className="mb-3">Our Team Members</h1>
                    <p className="mb-1">Vero justo sed sed vero clita amet. Et justo vero sea diam elitr amet ipsum eos
                      ipsum clita duo sed. Sed vero sea diam erat vero elitr sit clita.</p>
                  </div>
                  <div className="row g-4">
                    <div className="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                      <div className="team-item border-top border-5 border-primary rounded shadow overflow-hidden">
                        <div className="text-center p-4">
                          <img className="img-fluid rounded-circle mb-4" src="img/team-1.jpg" alt="" />
                          <h5 className="fw-bold mb-1">Full Name</h5>
                          <small>Designation</small>
                        </div>
                        <div className="d-flex justify-content-center bg-primary p-3">
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-facebook-f" /></a>
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-twitter" /></a>
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-instagram" /></a>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                      <div className="team-item border-top border-5 border-primary rounded shadow overflow-hidden">
                        <div className="text-center p-4">
                          <img className="img-fluid rounded-circle mb-4" src="img/team-2.jpg" alt="" />
                          <h5 className="fw-bold mb-1">Full Name</h5>
                          <small>Designation</small>
                        </div>
                        <div className="d-flex justify-content-center bg-primary p-3">
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-facebook-f" /></a>
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-twitter" /></a>
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-instagram" /></a>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
                      <div className="team-item border-top border-5 border-primary rounded shadow overflow-hidden">
                        <div className="text-center p-4">
                          <img className="img-fluid rounded-circle mb-4" src="img/team-3.jpg" alt="" />
                          <h5 className="fw-bold mb-1">Full Name</h5>
                          <small>Designation</small>
                        </div>
                        <div className="d-flex justify-content-center bg-primary p-3">
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-facebook-f" /></a>
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-twitter" /></a>
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-instagram" /></a>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.7s">
                      <div className="team-item border-top border-5 border-primary rounded shadow overflow-hidden">
                        <div className="text-center p-4">
                          <img className="img-fluid rounded-circle mb-4" src="img/team-4.jpg" alt="" />
                          <h5 className="fw-bold mb-1">Full Name</h5>
                          <small>Designation</small>
                        </div>
                        <div className="d-flex justify-content-center bg-primary p-3">
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-facebook-f" /></a>
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-twitter" /></a>
                          <a className="btn btn-square text-primary bg-white m-1" href="#"><i className="fab fa-instagram" /></a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </DefaultLayout>
        </div>
      </div>
    </>
  )
}
